export const USER_UPDATED = 'USER_UPDATED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_ERROR = 'USER_ERROR'

export const FETCH_MEMBERS = 'FETCH_MEMBERS'
export const UPDATE_MEMBER = 'UPDATE_MEMBER'
export const ADD_MEMBER = 'ADD_MEMBER'
export const REMOVE_MEMBER = 'REMOVE_MEMBER'
