export const USER_UPDATED = 'USER_UPDATED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_ERROR = 'USER_ERROR'

export const FETCH_MEMBERS = 'FETCH_MEMBERS'
export const UPDATE_MEMBER = 'UPDATE_MEMBER'
export const ADD_MEMBER = 'ADD_MEMBER'
export const REMOVE_MEMBER = 'REMOVE_MEMBER'

export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES'
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE'
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE'
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE'
